# name: Build and Push Frontend Docker Image

# on:
#   push:
#     branches:
#       - main
#       - develop
#     tags:
#       - 'v*'
#     paths:
#       - 'src/**'
#       - 'public/**'
#       - 'package*.json'
#       - 'vite.config.js'
#       - 'Dockerfile'
#       - '.github/workflows/frontend-docker.yml'
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'src/**'
#       - 'public/**'
#       - 'package*.json'
#       - 'vite.config.js'
#       - 'Dockerfile'

# env:
#   DOCKER_IMAGE: iyuyisenga/cherry-app-frontend-test

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     environment: DOCKER_IMAGE
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Extract metadata
#       id: meta
#       uses: docker/metadata-action@v5
#       with:
#         images: ${{ env.DOCKER_IMAGE }}
#         tags: |
#           # Branch event
#           type=ref,event=branch
#           # Tag event
#           type=ref,event=tag
#           # PR event
#           type=ref,event=pr
#           # Default latest for main branch
#           type=raw,value=latest,enable={{is_default_branch}}
#           # Custom version tag
#           type=raw,value=v1.0.1
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         platforms: linux/amd64,linux/arm64
#         push: true
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}
#         cache-from: type=gha
#         cache-to: type=gha,mode=max

#     - name: Image digest
#       run: echo ${{ steps.build-and-push.outputs.digest }}

name: Build, Push Frontend Docker Image and Update Samplecharts

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - 'vite.config.js'
      - 'Dockerfile'
      - '.github/workflows/frontend-docker.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - 'vite.config.js'
      - 'Dockerfile'

permissions:
  contents: write  # Required to push changes to the samplecharts repo

env:
  DOCKER_IMAGE: iyuyisenga/cherry-app-frontend-test
  SAMPLECHARTS_REPO: benitha200/samplecharts
  SAMPLECHARTS_PATH: charts/cherryapp-chart/values.yaml

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    environment: DOCKER_IMAGE

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create placeholder .env file
        run: touch .env 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clone samplecharts repo with token
        run: |
            git clone https://x-access-token:${{ secrets.SAMPLECHARTS_PAT }}@github.com/benitha200/samplecharts.git
    
      - name: Update frontend image tag in samplecharts values.yaml
        run: |
            TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
            VALUES_FILE="samplecharts/charts/cherryapp-chart/values.yaml"
            echo "Updating frontend image tag to ${TAG} in ${VALUES_FILE}"
            # Update only the second occurrence of 'tag:'
            sed -i '0,/tag:/!{0,/tag:/s/tag:.*/tag: '"${TAG}"'/}' "$VALUES_FILE"
            cat "$VALUES_FILE"

    
      - name: Commit and push updated values.yaml
        working-directory: samplecharts
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add charts/cherryapp-chart/values.yaml
            git commit -m "Update frontend image tag to ${GITHUB_REF_NAME}"
            git push origin main


